### ISSUE TITLE
Error: bundle exec rake db:setup

### ISSUE THREAD

**Issue by itsmechlark** [doorkeeper-gem/doorkeeper-provider-app#10]
<pre><code>
*****/doorkeeper-provider-app>bundle exec rake db:setup
rake aborted!
cannot load such file -- sqlite3/sqlite3_native
*****/doorkeeper-provider-app/config/application.rb:7:in `<top (required)>'
*****//doorkeeper-provider-app/Rakefile:5:in `require'
*****/doorkeeper-provider-app/Rakefile:5:in `<top (required)>'
(See full trace by running task with --trace)
</code></pre>

**Comment by nbulaj** [comment]
All application code base updated to Rails 5.1, rake tasks are fixed
