### ISSUE TITLE
Seed Data

### ISSUE THREAD

**Issue by philsturgeon** [doorkeeper-gem/doorkeeper-provider-app#17]
I was looking at the [Seed Data instructions](https://doorkeeper-provider.herokuapp.com/#seed-data) to see if I could bypass using the Application interface, as it's broken with Rails 4.2 (https://github.com/doorkeeper-gem/doorkeeper/issues/494).

The website says this: 

> The generated user email is user@example.com and password is doorkeeper.
> The application id and secret will show up on terminal when the script ends.
> After that, you can just fire up the rails server and you're ready to go.

When is this generated? I ran db:setup and saw no output. I ran `rake -T` and saw no doorkeeper tasks.

I'm a little wet around the ears with Rails sure, but this seems like a bit of a disconnect. 

How should I go about creating applications?

**Comment by nbulaj** [comment]
Hi @philsturgeon . The demo app was updated to Rails 5 and last stable version of Doorkeeper. Could you please check if tgis issue still actual? 

You can check travis config in order to see how data is seeded for test env

**Comment by philsturgeon** [comment]
I'm sure its fine, I dont work with this anymore. :)
