### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by amaranthrose** [doorkeeper-gem/doorkeeper-provider-app#19]
The app seems pretty behind the latest doorkeeper gem. Is it still maintained? There are also a few (quite old) unmerged PRs.

**Comment by wbreeze** [comment]
Same question. I did an update. See the PR here https://github.com/doorkeeper-gem/doorkeeper-provider-app/pull/20 and fork here https://github.com/wbreeze/doorkeeper-provider-app

**Comment by wbreeze** [comment]
Same question. I did an update. See the PR here https://github.com/doorkeeper-gem/doorkeeper-provider-app/pull/20 and fork here https://github.com/wbreeze/doorkeeper-provider-app

**Comment by wbreeze** [comment]
Same question. I did an update. See the PR here https://github.com/doorkeeper-gem/doorkeeper-provider-app/pull/20 and fork here https://github.com/wbreeze/doorkeeper-provider-app

**Comment by felipeelias** [comment]
I guess it is, I left the project long ago maybe some of the current maintainers could link to your fork?

**Comment by wbreeze** [comment]
Contributor @piotrj shows as a member of doorkeeper-gem. I think it has to be one of those four members shown. We are all so busy! It's hard to keep up.

**Comment by nbulaj** [comment]
With the big help of the @wbreeze it is updated to the latest stable versions of Rails and Doorkeeper gem 🎉 

The only problem is access to Heroku - it is required for somebody who has it to deploy and test new version in the cloud. @felipeelias ?
