### ISSUE TITLE
Demo app in heroku is broken

### ISSUE THREAD

**Issue by aquadrehz** [doorkeeper-gem/doorkeeper-provider-app#246]
Please check the following link
http://doorkeeper-provider.herokuapp.com/

<img width="724" alt="Screen Shot 2564-04-09 at 11 33 27" src="https://user-images.githubusercontent.com/3850078/114128827-79225700-9927-11eb-9672-0c296bdab3f8.png">

**Comment by nbulaj** [comment]
Fixed now and upgraded to Ruby 3 and Rails 7
Thanks!
