### ISSUE TITLE
RuntimeError in Doorkeeper::ApplicationsController#create

### ISSUE THREAD

**Issue by gabamnml** [doorkeeper-gem/doorkeeper-provider-app#4]
Your path has not been found. Didn't you mean to call routes.oauth_application_url in doorkeeper configuration blocks?

app/controllers/doorkeeper/applications_controller.rb:20:in `create'

This error happens when I try to create a new application.

**Comment by gayankasun** [comment]
is there any update regarding this issue.i have same issue  :(
