### ISSUE TITLE
redirect_url inconsistency with doorkeeper-devise-client

### ISSUE THREAD

**Issue by denispeplin** [doorkeeper-gem/doorkeeper-provider-app#9]
After installing both `doorkeeper-provider-app` (and running `db:setup`) and `doorkeeper-devise-client`, I'm start getting `The redirect uri included is not valid.` after authentication.

The solution is simple to go to `/oauth/applications` and to change `http://localhost:3000/callback`, which I've set up before based on initial setup, to `http://localhost:3000/users/auth/doorkeeper/callback`

I can't find this stuff mentioned in documentation, so maybe some initial setup is wrong.

**Comment by seyyah** [comment]
I have also this problem and solve it via @denispeplin solution.

```
http://PROVIDER_APP/oauth/applications/new
Application: test
Callback url: http://CLIENT_APP/users/auth/doorkeeper/callback
```

Thank you.

**Comment by nbulaj** [comment]
Don't sure is this issue still exists after update to Doorkeeper 4.2.6 and Rails 5, so currently closing it due to oldness. If somebody will face the problems - new issue are welcome.

Thanks!
